In [25]:
import numpy as np
#to open and read the file
file=np.loadtxt("RandomeValues.csv",delimiter=',')
print(file)

[[ 68.  54.  95.  65.  68.   6.  50.  63.  99.  81.  14.]
 [  5.  85.  83.  22.  39.  26.  73.  77.  97.  75.  33.]
 [  1.  46.  39.  53.  67.  19.  87.   3.  84.  58.  26.]
 [ 83.  81.  31.  96.  13.   3.  58.  32. 100. 100.  96.]
 [ 71.   2.  63.  84.  85.   5.  67.  35.  76.  77.  76.]
 [ 79.  67.  44. 100.  89.  71.  27.  46.  45.  13.  32.]
 [100.  27.  23.  76.  53.  86.   2.  59.  30.  52.   2.]
 [ 37.  43.  10.  16.  77.  40.  62.   4.  22.  64.  15.]
 [ 97.  61.   8.  99.  67.  42.  59.   7.  86.  42.  21.]
 [ 80.  93.  76.  46.  46.  35.  57.  70.  93.  36.  86.]
 [ 25.  23.  89.  58.  89.  52.  21.  65.  52.  25.  45.]]


In [26]:
#Retreive rows 5,7,9
rows=np.array([file[5],file[7],file[9]])

In [27]:
print(rows)

[[ 79.  67.  44. 100.  89.  71.  27.  46.  45.  13.  32.]
 [ 37.  43.  10.  16.  77.  40.  62.   4.  22.  64.  15.]
 [ 80.  93.  76.  46.  46.  35.  57.  70.  93.  36.  86.]]


In [28]:
#Reteive columns 0,7,11
columns=np.array([file[:,0],file[:,7],file[:,10]])

In [29]:
print(columns)

[[ 68.   5.   1.  83.  71.  79. 100.  37.  97.  80.  25.]
 [ 63.  77.   3.  32.  35.  46.  59.   4.   7.  70.  65.]
 [ 14.  33.  26.  96.  76.  32.   2.  15.  21.  86.  45.]]


In [32]:
#Retreiving rows and columns simultaneously
coll=np.array([file[:,[1,2,7,8,9]]])

In [33]:
print(coll)

[[[ 54.  95.  63.  99.  81.]
  [ 85.  83.  77.  97.  75.]
  [ 46.  39.   3.  84.  58.]
  [ 81.  31.  32. 100. 100.]
  [  2.  63.  35.  76.  77.]
  [ 67.  44.  46.  45.  13.]
  [ 27.  23.  59.  30.  52.]
  [ 43.  10.   4.  22.  64.]
  [ 61.   8.   7.  86.  42.]
  [ 93.  76.  70.  93.  36.]
  [ 23.  89.  65.  52.  25.]]]
