In [28]:
#ACTIVITY 1 EX1

#A small Numpy array to generate 10000 random numbers in a 2D array
import numpy as np
r=np.random.random((100,100))
print("2D 10,000 random numbers:",r)
#Note 100 * 100 will give us 10,000 numbers

print("")

#For each, calculate the square root
sqroot=np.sqrt(r)
print("sqroot is",sqroot)

print("")

#Sum all these calculations
total = np.sum(sqroot)
print("total is",total)


2d 10000 random numbers: [[0.35234209 0.29706861 0.42917751 ... 0.05474508 0.68922872 0.12579771]
 [0.61107532 0.53301756 0.77995915 ... 0.27600095 0.02487196 0.86963341]
 [0.63438724 0.62590827 0.28763581 ... 0.97574066 0.93983881 0.32781442]
 ...
 [0.84138593 0.39292088 0.6533694  ... 0.72071622 0.66806564 0.62078882]
 [0.5652913  0.13714977 0.23692861 ... 0.15598134 0.30710583 0.97612002]
 [0.36750582 0.23753517 0.43402872 ... 0.03102334 0.09468639 0.61868302]]

sqroot is [[0.5935841  0.54504001 0.65511641 ... 0.23397667 0.830198   0.35467973]
 [0.78171307 0.73008052 0.88315296 ... 0.52535792 0.15770847 0.93254137]
 [0.7964843  0.79114365 0.5363169  ... 0.98779586 0.96945284 0.5725508 ]
 ...
 [0.91727091 0.62683401 0.80831269 ... 0.84895007 0.81735283 0.78790153]
 [0.75185856 0.37033737 0.48675313 ... 0.39494473 0.5541713  0.98798786]
 [0.60622258 0.4873758  0.65880856 ... 0.17613443 0.30771154 0.78656406]]

total is 6673.322575547909
